language: perl
perl:
  - "5.26"

branches:
  exclude:
  - /^dev-.*$/

env: 
  - COVERAGE=1

sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov

script:
  - perl Makefile.PL
  - make test
  - cover -test

after_success:
  - cover -report codecov
