language: perl
perl:
  - "5.26"

branches:
  exclude:
  - /^dev-.*$/

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov

script:
  - perl Build.PL
  - ./Build build
  - cover -test

after_success:
  - cover -report codecov
